### ISSUE TITLE
TravisCI compiler matrix feature

### ISSUE THREAD

**Issue by mjtrangoni** [NagiosEnterprises/nagioscore#520]
Hi @hedenface,

I think [this](https://docs.travis-ci.com/user/languages/cpp/) matrix could be interesting for your TravisCI builds.

You can do something like I did [here](https://github.com/ArcticaProject/nx-libs/blob/3.6.x/.travis.yml), and you can also test **Linux** as well as **OSX**!

Another thing you could double-check is your actual compiler flags against [this](https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc) article, and use them with the newest GCCs.

**Comment by hedenface** [comment]
One thing that I don't understand is the specification of trusty at the top, outside of the matrix. Does this just ensure that each of the linux distros are trusty? So that you don't have to specify it for each one?

**Comment by mjtrangoni** [comment]
@hedenface Yes! A year ago was also Precise (Ubuntu 12.04) there. Unfortunately it seems that Travis is really behind with the OSs, see [#5821](https://github.com/travis-ci/travis-ci/issues/5821). OTOH, you can test with old and new GCC versions as well, and also with OSX.

Note: I did not ever test a Linux + OSX matrix scheme.

**Comment by hedenface** [comment]
This is pretty neat. I've got the start of a matrix now :)

Those documents they provide are helpful, but is there a better way of determining what packages can be installed other than trial and error?

**Comment by hedenface** [comment]
See here: https://travis-ci.org/NagiosEnterprises/nagioscore/jobs/387756217

It installs gcc5, but the MATRIX_EVAL isn't used it seems like (because of the `gcc --version` printing 4.8)

**Comment by mjtrangoni** [comment]
Hi @hedenface,

Take a look [here](https://travis-ci.org/ArcticaProject/nx-libs/jobs/383093698). 'CC=gcc-5' is what you have to look for.  

By the way, I see you are making a `$ eval "${MATRIX_EVAL}"` before the local CC=gcc, and this should happen after that, otherwise you are using the system one.

**Comment by hedenface** [comment]
Not sure what you mean. Here is the current file:

```
language: c

sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - build-essential
            - apache2
            - php5
            - php5-gd
            - libgd-dev
            - unzip
            - lcov
            - gperf
            - gcovr

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - apache2
            - php5
            - php5-gd
            - libgd-dev
            - unzip
            - lcov
            - gperf
            - gcovr
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5"

script:
  - ./configure --enable-testing
  - make test
  - gcovr -r .
```
